# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_pb2 as image__pb2


class GRPCImageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImageSync = channel.unary_unary(
                '/image.GRPCImage/ProcessImageSync',
                request_serializer=image__pb2.Request.SerializeToString,
                response_deserializer=image__pb2.Response.FromString,
                )
        self.ProcessImageStreaming = channel.stream_stream(
                '/image.GRPCImage/ProcessImageStreaming',
                request_serializer=image__pb2.Request.SerializeToString,
                response_deserializer=image__pb2.Response.FromString,
                )


class GRPCImageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessImageSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessImageStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCImageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImageSync': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImageSync,
                    request_deserializer=image__pb2.Request.FromString,
                    response_serializer=image__pb2.Response.SerializeToString,
            ),
            'ProcessImageStreaming': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessImageStreaming,
                    request_deserializer=image__pb2.Request.FromString,
                    response_serializer=image__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image.GRPCImage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCImage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessImageSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.GRPCImage/ProcessImageSync',
            image__pb2.Request.SerializeToString,
            image__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessImageStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/image.GRPCImage/ProcessImageStreaming',
            image__pb2.Request.SerializeToString,
            image__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
